[build]
    command = "npm run netlify"
    publish = "public"
    functions = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200


[[redirects]]
    from = "/facebook"
    to = "https://facebook.com/dailytexascountry"
    status = 301

[[redirects]]
    from = "/twitter"
    to = "https://twitter.com/dailytxcountry"
    status = 301

[[redirects]]
    from = "/instagram"
    to = "https://instagram.com/dailytexascountry"
    status = 301

[[redirects]]
    from = "/youtube"
    to = "https://youtube.com/channel/UCpbIlFaiv-3188nAWtgL0Iw"
    status = 301

[[redirects]]
    from = "/apple-music"
    to = "https://music.apple.com/us/playlist/daily-texas-country/pl.u-leyl0Y6tMkvW2oL"
    status = 301

[[plugins]]
    package = "netlify-plugin-gatsby-cache"
