name: "🥃 whiskey wednesday"

on:
    schedule:
        # utc time zone
        # every thursday @ 1am cst
        - cron: "0 6 * * 4"
    workflow_dispatch:

jobs:
    rebuild:
        name: "♻ rebuild"
        runs-on: ubuntu-latest
        steps:
            - name: "🎣 webhook"
              uses: joelwmale/webhook-action@2.1.0
              with:
                  url: ${{ secrets.NETLIFY_BUILD_HOOK }}
