name: "🥃 whiskey wednesday"

on:
    schedule:
        # utc time zone
        # every thursday @ 1am cst
        - cron: "0 6 * * 4"
    workflow_dispatch:

jobs:
    rebuild:
        name: "♻ rebuild"
        runs-on: ubuntu-latest
        steps:
            - name: "🎣 webhook"
              uses: joelwmale/webhook-action@2.0.2
              with:
                  url: https://api.netlify.com/build_hooks/5ec53c98799bd3b4f89dbb09
